### ISSUE TITLE
[FIXED PRICE CONTRACT]: Developer Community Insights Dashboard [ISSUE IN PROGRESS]

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1014]
### 📃 Description

The DCI dashboard helps dev rels to understand and measure the effectiveness of hackathons, community programs, webinars, conferences or bootcamps.

The dashboard will facilitate these statistics based on activity on Github.

### 👨‍⚖️ Acceptance Criteria

Where is the code going to be located:

- [ ] Everything that will be developed for this EPIC will be located in a separate branch called dci-dashboard
- [ ] The project code will be located in the pages directory (https://github.com/OpenQDev/OpenQ-Frontend/tree/production/pages) create a new folder named dci and create a new index.js file to start with, this is where the campaign manager dashboard will be found

Campaign Manager Dashboard:
Before you can add repositories and analyze their activities you first want to be able to create a new campaign as in Mockup ( ) shown. This will enable the user to compare various events with each other. Each campaign could be for example a hackathon. 

- [ ] Add campaign will enable to create a new campaign. For now we only want to be able to select a name for the campaign
- [ ] After a campaign has been added we want to be able to enter into the campaign dashboard
- [ ] If we add new repositories to a campaign we want to be able to see in the campaign manager dashboard the amount of repositories we are watching and a summary of all developers working on all those repositories. Additionally we want to see the amount of commits that have been done within that campaign and the date the campaign was created

Repository Dashboard:

- [ ] As you can see in the next Mockup (A1), This will be an overview of repositories. To get started create a modal that will be activated with the "Add repo" button
- [ ] In here the user can insert a repository which will be fetched and shown as in Mockup (A2)
- [ ] Clicking on the "Confirm" button adds this repository to the dashboard and will store it in our database
- [ ] The user can now see the repo name, a description, icons of the developer building the repo, and most importantly how many commits they have done this week
- [ ] The main goal now is to be able to add more repos and compare each repo with each other by activity
- [ ] The sorting feature can filter repos by highest activity today, this week, this month and this year

Developer Dashboard:

- [ ] The developer dashboard shows as in Mockup ( ) all developers that are working on repositories that were added
- [ ] The information displayed is: Profile picture (github), name, repositories actively worked on.
