### ISSUE TITLE
Supercharging Contests

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1143]
# Supercharging Contests

## Description
To support the features requested by hackathon sponsors, I am proposing a few major updates.

These updates will not change anything about our current contest setup. It will be an additional tool that we will offer.

First of all, this tool will only be available to people who are on a whitelist. It will be accessible through the Profile dropdown menu -> For Organizations  (or something else, I'm not sure what we'll call it yet).

- [x] Add in our admin page a way to whitelist users for the hackathon organization page

![Hackathon Organizer Dashboard](https://user-images.githubusercontent.com/28826387/210594459-49c8c0ad-3732-4a40-8bbd-d8e5a4be6855.png)

if you are already organizing a hackathon, this dashboard will look like this. Here you can manage them or create new ones

**Create a new hackathon page:**

![Create Hackathon](https://user-images.githubusercontent.com/28826387/210594470-301743a0-2594-4cdb-bc4a-86b0d64dca0c.png)

- [x] attend link

- [x] #1671

**View section:**

![Hackathon View](https://user-images.githubusercontent.com/28826387/210594491-034554e9-292f-4b50-826c-cd58dae5ffe3.png)

**Bounty section:**

![Hackathon Bounty](https://user-images.githubusercontent.com/28826387/210594517-fb47a1de-cb07-45a0-b32c-036cc7060f00.png)

**Bounty creation modal**

- [x] alternative bounty name (stored on-chain as string)
- [x] alternative logo (github organization link)

- [x] #1670

![Hackathon Submissions](https://user-images.githubusercontent.com/28826387/210594537-4132a619-8390-4ccb-a9a9-d1f5caf45b0c.png)

- [x] submissions (PR) have a:
- repo link
- Thumbnail Image

Step Submission Process:

- [x] #1669

![Hackathon Submissions Page](https://user-images.githubusercontent.com/28826387/210594598-ccd1a036-8aaa-46a4-bb5f-bdf72b8e00d5.png)

- [x] #1668

![Hackathon Explore](https://user-images.githubusercontent.com/28826387/210594655-b88d736d-d0d4-457c-8fa0-66f99b1daea7.png)

**Comment by Christopher-Stevers** [comment]
@rickkdev , been working on this now that the Eth Denver stuff is pretty much wrapped up. 
What would this page be representing?
![image](https://user-images.githubusercontent.com/72156679/225072823-2a790834-2667-48ba-b41b-db4bf7f9057a.png)

A hackathon represents a repository, so I'd assume it represents the repository, but it says "0x . . . minted this contract on December 12 . . . "  so that would only apply to individual bounties.

**Comment by Christopher-Stevers** [comment]
Also wondering where we'd be getting this data from:
![image](https://user-images.githubusercontent.com/72156679/225418894-461db810-f16a-40db-acf3-7cc0a3984e7c.png)
Would that be a sum of budgets (currently impossible) or a number entered in when creating the repository?
